### ISSUE TITLE
React 18 projects throw a peer dependency error when installing @userfront/react

### ISSUE THREAD

**Issue by GeorgeCodes19** [userfront/userfront-react#19]
@userfront/react binding has peer dependencies on React 17.0.1 and React-Dom 17.0.1 which may be throwing a peer dependency issue when installing on React 18 projects. 

`  "peerDependencies": {
    "react": "^17.0.1",
    "react-dom": "^17.0.1"
  } `

![Screen Shot 2022-04-06 at 3 54 03 PM](https://user-images.githubusercontent.com/7874385/162059722-22d35f8d-8f4d-4c18-aa60-24e7cb94ce21.png)

**Possible solution**

` "peerDependencies": {
  "react": "18.0.* || ^17.0.1",
  "react-dom": "18.0.* || ^17.0.1"
}`

**Comment by RJFelix** [comment]
We're now using React 18 in DDG (with a dependency override) so we'll get a little real-world testing before the upgrade.

18 drops IE11 support, but admins who support IE11 won't upgrade, so that's fine. I don't see any other breaking changes of interest.
