### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by drac94** [userfront/userfront-react#20]
Are there any plans to add typescript support?

**Comment by tyrw** [comment]
> Are there any plans to add typescript support?

Yes there are. We will be overhauling the library in 1-2 months and will include a host of new standalone components (e.g. granular components like `<EmailInput/>` in addition to `<SignupForm/>`).

As part of this overhaul, we will also add TypeScript support.

**Comment by adriangabardo** [comment]
It's now June 2023, has this been added? I can't see any documentation on your website and it will be a key factor in deciding to use Userfront or not

**Comment by RJFelix** [comment]
Hi @adriangabardo,

This library currently does two things.

1. Pass through our Core JS library [@userfront/core](https://github.com/userfront/userfront-core). The Core JS library includes [type definitions](https://github.com/userfront/userfront-core/tree/main/ts). So all of the methods in our [Core JS docs](https://userfront.com/docs/js) should have type defs available. Do these work for you?

2. Wraps our Toolkit in a React component when you call `Userfront.build`. There's no explicit type defs delivered for this, but the result is a plain React (class) component that takes no props.

We have a new React Toolkit coming very shortly that is written entirely in TypeScript, so should have TS support out of the box - I'll update when that is available.

I hope this helps! Feel free to tag me with any other questions or concerns.
