### ISSUE TITLE
toolkit LoginForm redirect parameter

### ISSUE THREAD

**Issue by Curtis-rmc-06** [userfront/userfront-react#24]
Currently, there isn't a way to provide a programmatic redirect using the toolkit `<LoginForm/>`.

In order to implement programmatic redirects, you need to either:

1.  build your own form and use the core `login()` method with the redirect parameter, which is a pain when there is already an excellent option; or
2. Use cookies to manage state and set the login redirect to a page that redirects based on the cookie.  This adds unnecessary bloat and page loads.

Is it possible to implement some form of redirect parameter?  Since I believe this form is dynamic and multipurpose, I suggest something like `<LoginForm redirect={{
login: '/path', ...other options to support other uses
}}/>`

Unless #14 will be able to handle this?

**Comment by tyrw** [comment]
Yes, #14 will handle a parameter passed directly.

Currently, you should be able to do a redirect with a querystring in the URL. E.g. if your form is located at 

`https://example.com/login?redirect=/custom`

Then when the login succeeds, the browser will redirect to `https://example.com/custom`

**Comment by RJFelix** [comment]
Added in `@userfront/toolkit v1.x.x`.
