### ISSUE TITLE
Get login link for initial page loads

### ISSUE THREAD

**Issue by kaitok** [userfront/userfront-react#30]
I use the ["Get login link" feature](https://userfront.com/guide/automatic-login-form-react#login-link) as main login function, but is there an option to initially display this "Get login link" when the page loads?

**Comment by tyrw** [comment]
Thanks for asking, and yes this is now possible. We released a new toolkit that has the ability to show only the "Get login link" button, or to place it above other options. You can view installation instructions for the new toolkit at https://userfront.com/dashboard/toolkit
